[package]
name = "prisma-client-rust"
version = "0.5.3"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
description = "A prisma client for Rust"
license = "MIT"

exclude = ["examples", "integration-tests"]

[workspace]
members = ["examples/*", "integration-tests", "sdk", "cli", "prisma-cli"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"
bigdecimal = { version = "0.2.2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }
indexmap = "1.8.2"
serde-value = "0.7.0"

query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
query-connector = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
user-facing-errors = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
