[package]
name = "prisma-client-rust"
version = "0.4.1"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
description = "A prisma client for Rust"
license = "MIT"

exclude = [
    "examples",
    "integration-tests"
]

[workspace]
members = [
    "examples/*",
    "integration-tests",
    "cli",
    "prisma-cli"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"

query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "8b94a80a2d8f12a2916fe28e3218162aa71e8539" }
query-connector = { git = "https://github.com/Brendonovich/prisma-engines", rev = "8b94a80a2d8f12a2916fe28e3218162aa71e8539" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "8b94a80a2d8f12a2916fe28e3218162aa71e8539" }
datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "8b94a80a2d8f12a2916fe28e3218162aa71e8539" }

[dev-dependencies]
rand = "0.8.5"

[profile.test]
debug = 0
