[package]
name = "prisma-client-rust"
version = "0.2.0"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2018"
description = "A prisma client for Rust"
license = "MIT"

exclude = [
    "examples"
]

[workspace]
members = [
    "codegen",
    "core",
    "examples/*"
]

[dependencies]
prisma-client-rust-core = { path = "./core", version = "0.2.0" }
prisma-client-rust-codegen = { path = "./codegen", version = "0.2.0" }
serde_json = "1.0.79"
serde_path_to_error = "0.1.7"
