[package]
name = "prisma-client-rust"
version = "0.6.1"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
description = "A prisma client for Rust"
license = "MIT"
rust-version = "1.62"

exclude = ["examples", "integration-tests"]

[features]
default = []
rspc = ["dep:rspc"]
sqlite-create-many = ["datamodel/sqlite-create-many"]
migrations = ["quaint", "migration-core", "sql-migration-connector", "mongodb-migration-connector", "include_dir", "tempdir", "tokio", "enumflags2", "tracing"]

[workspace]
members = ["examples/*", "integration-tests", "sdk", "cli", "prisma-cli"]
resolver = "2"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"
bigdecimal = { version = "0.2.2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }
indexmap = "1.8.2"
serde-value = "0.7.0"
base64 = "0.13.0"

query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
query-connector = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
user-facing-errors = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
dmmf = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }
schema = { git = "https://github.com/Brendonovich/prisma-engines", rev = "51d3b4bb966f7a5d29b4059822af6dd1d3c9642c" }

quaint = { git = "https://github.com/prisma/quaint.git", optional = true, features = ["sqlite", "postgresql", "mysql", "mssql"] }
migration-core = { git = "https://github.com/Brendonovich/prisma-engines.git", optional = true }
sql-migration-connector = { git = "https://github.com/Brendonovich/prisma-engines.git", optional = true }
mongodb-migration-connector = { git = "https://github.com/Brendonovich/prisma-engines.git", optional = true }
include_dir = { version = "0.7.2", optional = true }
tempdir = { version = "0.3.7", optional = true }
tokio = { version = "1.21.0", features = ["fs"], optional = true }
enumflags2 = { version = "0.7.5", optional = true }
tracing = { version = "0.1.36", optional = true }

rspc = { version = "0.0.5", optional = true, features = [
  "indexmap",
  "chrono",
  "uuid",
] }
