[package]
name = "prisma-client-rust"
version = "0.6.1"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
description = "A prisma client for Rust"
license = "MIT"
rust-version = "1.62"

exclude = ["examples", "integration-tests"]

[features]
default = []
rspc = ["dep:rspc"]
sqlite-create-many = ["datamodel/sqlite-create-many"]
migrations = [
  "migration-core",
  "include_dir",
  "tempdir",
  "tokio",
  "tracing",
]

[workspace]
members = ["examples/*", "integration-tests", "sdk", "cli", "prisma-cli"]
resolver = "2"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"
bigdecimal = { version = "0.2.2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }
indexmap = "1.8.2"
serde-value = "0.7.0"
base64 = "0.13.0"

query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
query-connector = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
user-facing-errors = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
dmmf = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }
schema = { git = "https://github.com/Brendonovich/prisma-engines", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada" }

# features = "migrations"
migration-core = { git = "https://github.com/Brendonovich/prisma-engines.git", rev = "1a9235ce5c50bb629cb63235ca8b5ca82198cada", optional = true }
include_dir = { version = "0.7.2", optional = true }
tempdir = { version = "0.3.7", optional = true }
tokio = { version = "1.21.0", features = ["fs"], optional = true }
tracing = { version = "0.1.36", optional = true }

# features = "rspc"
rspc = { version = "0.0.5", optional = true, features = [
  "indexmap",
  "chrono",
  "uuid",
] }
