[package]
name = "prisma-client-rust"
version = "0.6.1"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
description = "A prisma client for Rust"
license = "MIT"
rust-version = "1.62"

exclude = ["examples", "integration-tests"]

[features]
default = ["mysql", "sqlite", "mssql", "postgresql", "mongodb"]
rspc = ["dep:rspc"]
sqlite-create-many = ["datamodel/sqlite-create-many"]

mysql = ["query-core/mysql", "datamodel/sql"]
sqlite = ["query-core/sqlite", "datamodel/sql"]
mssql = ["query-core/mssql", "datamodel/sql"]
postgresql = ["query-core/mssql", "datamodel/sql"]
mongodb = ["query-core/mongodb", "datamodel/mongodb"]

[workspace]
members = ["examples/*", "integration-tests", "sdk", "cli", "prisma-cli"]
resolver = "2"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"
bigdecimal = { version = "0.2.2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }
indexmap = "1.8.2"
serde-value = "0.7.0"
base64 = "0.13.0"

query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
query-connector = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
user-facing-errors = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
dmmf = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }
schema = { git = "https://github.com/Brendonovich/prisma-engines", rev = "75911613d4b8684840d656db22a25d9d3fb24414" }

rspc = { version = "0.0.5", optional = true, features = [
  "indexmap",
  "chrono",
  "uuid",
] }
