[package]
name = "specta-example"
version = "0.1.0"
edition = "2021"
# change to whatever you name your package
default-run = "specta-example"

[dependencies]
prisma-client-rust = { features = ["rspc"], path="../../" }
serde = { version = "1.0", features = ["derive"] }
