[package]
name = "prisma-client-rust-cli"
version = "0.5.3"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"

[dependencies]
serde_path_to_error = "0.1.7"
quote = "1.0.18"
syn = "1.0.91"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

prisma-client-rust-sdk = { path = "../sdk" }

datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
request-handlers = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "4bd782c1597ec84d8ed70082b8b2995df6a6f8d2" }
proc-macro2 = "1.0.39"
