[package]
name = "prisma-client-rust-cli"
version = "0.6.0"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"

[features]
default = []
rspc = []

[dependencies]
serde_path_to_error = "0.1.7"
quote = "1.0.18"
syn = "1.0.91"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
proc-macro2 = "1.0.39"

prisma-client-rust-sdk = { path = "../sdk" }

datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "596bcf09a33adcd50624167aae4348153f07fe18" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "596bcf09a33adcd50624167aae4348153f07fe18" }
request-handlers = { git = "https://github.com/Brendonovich/prisma-engines", rev = "596bcf09a33adcd50624167aae4348153f07fe18" }
query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "596bcf09a33adcd50624167aae4348153f07fe18" }

