version: "3"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db:
