[package]
name = "actix-example"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust = { path = "../../", features = ["migrations"] }
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"
