[package]
name = "prisma-client-rust-sdk"
version = "0.6.0"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
rust-version = "1.62"

[dependencies]
convert_case = "0.5.0"
http = "0.2.6"
directories = "4.0.1"
flate2 = "1.0.23"
regex = "1.5.5"
serde_path_to_error = "0.1.7"
quote = "1.0.18"
reqwest = { version = "0.11.10", features = ["blocking"] }
syn = "1.0.91"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "dcea2c532cb777afb290a613f769140647a16804" }
prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "dcea2c532cb777afb290a613f769140647a16804" }
request-handlers = { git = "https://github.com/Brendonovich/prisma-engines", rev = "dcea2c532cb777afb290a613f769140647a16804" }
query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "dcea2c532cb777afb290a613f769140647a16804" }
dmmf = { git = "https://github.com/Brendonovich/prisma-engines", rev = "dcea2c532cb777afb290a613f769140647a16804" }

proc-macro2 = "1.0.39"
