[package]
name = "prisma-client-rust-sdk"
version = "0.6.3"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2021"
rust-version = "1.62"

[features]
default = ["mysql", "sqlite", "mssql", "postgresql", "mongodb"]

mysql = ["query-core/mysql"]
sqlite = ["query-core/sqlite"]
mssql = ["query-core/mssql"]
postgresql = ["query-core/postgresql"]
mongodb = ["query-core/mongodb"]

sqlite-create-many = ["psl/sqlite-create-many"]

[dependencies]
convert_case = "0.5.0"
serde_path_to_error = "0.1.7"
quote = "1.0.18"
syn = "1.0.91"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
proc-macro2 = "1.0.39"
thiserror = "1.0.37"

# prisma-models = { git = "https://github.com/Brendonovich/prisma-engines", rev = "06a1b97ff1ca597521ec9f3d10c1e274065f5e93" }
# datamodel = { git = "https://github.com/Brendonovich/prisma-engines", rev = "06a1b97ff1ca597521ec9f3d10c1e274065f5e93" }
# request-handlers = { git = "https://github.com/Brendonovich/prisma-engines", rev = "06a1b97ff1ca597521ec9f3d10c1e274065f5e93" }
# query-core = { git = "https://github.com/Brendonovich/prisma-engines", rev = "06a1b97ff1ca597521ec9f3d10c1e274065f5e93" }
# dmmf = { git = "https://github.com/Brendonovich/prisma-engines", rev = "06a1b97ff1ca597521ec9f3d10c1e274065f5e93" }

prisma-models = { path = "../../prisma-engines/query-engine/prisma-models" }
request-handlers = { path = "../../prisma-engines/query-engine/request-handlers" }
query-core = { path = "../../prisma-engines/query-engine/core" }
dmmf = { path = "../../prisma-engines/query-engine/dmmf" }
dml = { path = "../../prisma-engines/libs/dml" }
psl = { path = "../../prisma-engines/psl/psl" }
